####################################
# 데이터베이스 설정
####################################
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_login?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 1234

####################################
# 카카오 설정
####################################
kakao:
  client:
    id: 159bd3492eb75e050b8a1a3f7b8168e2
    secret: 055d26ac9f574c9d44c22bdea09dbd38
  redirect:
    url: http://localhost:8080/kakao/callback