####################################
# ?? ? ???? ?? ??
####################################
server:
  servlet:
    encoding:
      charset: UTF-8          # ?? ??? ??
      force: true             # ?? ??

spring:
  application:
    name: springboot-login     # ????? ??

  devtools:
    livereload:
      enabled: true           # ?? ??? ??
    restart:
      enabled: true           # ?? ??? ??
      preserve-session: true  # ?? ?? ??

  thymeleaf:
    cache: false              # ?? ??

  ####################################
  # ?????? ??
  ####################################
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_login?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 1234

  ####################################
  # JPA ??
  ####################################
  jpa:
    open-in-view: true      #
    hibernate:
      ddl-auto: create  #, update, ...
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy # ????? ???? ??? ??
    show-sql: true          # SQL ?? ???
    properties:
      hibernate:
        format_sql: true    # ?? ???? ???
        default_batch_fetch_size: 1000  # ??? ??? ??? ? in ?? ?? ??
    #database-platform: org.hibernate.dialect.MySQL8Dialect  # MySQL8 ?? ??

####################################
# ?? ?? ??
####################################
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace  # ???? ??? ???? ??

####################################
# ??? ???
####################################
kakao:
  client:
    id: 159bd3492eb75e050b8a1a3f7b8168e2
    secret: 055d26ac9f574c9d44c22bdea09dbd38
  redirect:
    url: http://localhost:8080/kakao/callback
